apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: codegen-100302
  janus-idp.io/tekton: codegen-100302
  backstage.io/kubernetes-id: codegen-100302
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: codegen-100302
resources:
- application-dev.yaml
- application-tekton.yaml