apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: codegen-100302
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/codegen-100302:da698d8f290bf0cd41b3c0a07cf1058eb6a99302@sha256:e3a9c07f61c4ccc1da48ce3aa0683979cc3eaba6a9a681726c7f56c563356257 # use pre-built to bootstrap
          name: app-inference
